#!/bin/sh
set +e
rm -rf .coverage
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
MIN_PERCENTAGE=100
echo "Working directory: $SCRIPTPATH"
export PYTHONPATH="$SCRIPTPATH:$PYTHONPATH"
coverage3 run -m nose --cover-package=src/stomp -w tests $@ -x && \
coverage3 report --include=src/stomp/* \
    --omit "./tests/*" \
    --omit "./src/stomp/test/*" \
    --fail-under $MIN_PERCENTAGE -m

coverage2 run -m nose --cover-package=src/stomp -w tests $@ && \
coverage2 report --include=src/stomp/* \
    --omit "./tests/*" \
    --omit "./src/stomp/test/*" \
    --fail-under $MIN_PERCENTAGE -m

